# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Flight.destroy_all
User.destroy_all
Destination.destroy_all

u1 = User.create(name: "User1")

d1 = Destination.create(location: "Maya Bay, Thailand", img_url: "https://www.hawaiipublicradio.org/sites/khpr/files/styles/x_large/public/201803/maya_bay_thailand.jpg", description: "Maya Bay in Phi Phi Everything you need to know about Maya Bay Hotels Flights   Flight + Hotel Things To Do Going to Check in Check out SEARCH Maya Bay is a stunningly beautiful bay that's sheltered by 100-metre high cliffs on three sides. Inside the bay there are several beaches, most are small and some only exist at low tide. The main one is around 200 metres long with silky soft white sand, underwater colourful coral and exotic fish in exceptionally clear water; the whole bay is one big reef.")
d2 = Destination.create(location: "Tokyo", img_url: "https://img.traveltriangle.com/blog/wp-content/uploads/2019/07/cover-for-Tokyo-In-October.jpg", description: "A beautiful mixture of traditional and modern, Tokyo is a city that will leave you awestruck. From tall skyscrapers to unique temples, you will find everything in the city. It is the place where technology meets nature and the result is commendable. And if you wish to witness the surreal side of the capital city, then visit Tokyo in October. The weather during October is simply perfect to have fun and an amazing day out. Here you will find reasons to visit Tokyo in the month of October and plan a heartwarming holiday.")
d3 = Destination.create(location: "Tower of London", img_url: "https://www.fodors.com/wp-content/uploads/2017/10/Ultimate-Things-To-Do-London-Tower-of-London-1-768x512.jpg", description: "With a gory 950-year history of beheadings, imprisonments, and torture, England’s most perfect medieval fortress and home of the Crown Jewels is shrouded in myth and legend. Established in 1078 by William the Conqueror, the Tower of London comprises 22 ancient towers in a fortified 18-acre site. It has been a palace, prison, and place of execution and has housed the Royal Armouries, the Royal Mint, and the Royal Menagerie. It’s still the only place you can see the 23,587 gemstones and full Coronation Regalia of the Royal Collection, including 10 dazzling crowns.")
d4 = Destination.create(location: "Venice", img_url: "https://www.kirkerholidays.com/media/image-cache/9011311b-3aa8-412b-9250-4902262164b5/780-840-1-4096-2234/1535468043-nicolo-di-giovanni-509932-unsplash2jpg.jpg", description: "Venice, the capital of northern Italy’s Veneto region, is built on more than 100 small islands in a lagoon in the Adriatic Sea. It has no roads, just canals – including the Grand Canal thoroughfare – lined with Renaissance and Gothic palaces. The central square, Piazza San Marco, contains St. Mark’s Basilica, which is tiled with Byzantine mosaics, and the Campanile bell tower offering views of the city’s red roofs.")
d5 = Destination.create(location: "Cape Town" , img_url: "https://media.timeout.com/images/105237728/image.jpg", description: "Cape Town is a port city on South Africa’s southwest coast, on a peninsula beneath the imposing Table Mountain. Slowly rotating cable cars climb to the mountain’s flat top, from which there are sweeping views of the city, the busy harbor and boats heading for Robben Island, the notorious prison that once held Nelson Mandela, which is now a living museum.")
d6 = Destination.create(location: "Marrakesh", img_url: "https://www.planetware.com/wpimages/2019/04/morocco-marrakesh-top-attractions-marrakesh-tanneries.jpg", description: "Marrakesh, a former imperial city in western Morocco, is a major economic center and home to mosques, palaces and gardens. The medina is a densely packed, walled medieval city dating to the Berber Empire, with mazelike alleys where thriving souks (marketplaces) sell traditional textiles, pottery and jewelry. A symbol of the city, and visible for miles, is the Moorish minaret of 12th-century Koutoubia Mosque.")
d7 = Destination.create(location: "Milford Sound", img_url: "https://www.milford-sound.co.nz/wp-content/uploads/2017/05/Milford-Sound-aerial-view.jpg", description: "Milford Sound is a fiord in the southwest of New Zealand’s South Island. It’s known for towering Mitre Peak, plus rainforests and waterfalls like Stirling and Bowen falls, which plummet down its sheer sides. The fiord is home to fur seal colonies, penguins and dolphins. Milford Discovery Centre and Underwater Observatory offers views of rare black coral and other marine life. Boat tours are a popular way to explore.")
d8 = Destination.create(location: "Bora Bora", img_url: "https://dbijapkm3o6fj.cloudfront.net/resources/1608,1004,1,6,4,0,960,540/-4153-/20190810121416/stay-minimum-3-nights-save-25-with-breakfast-included-bora-bora-pearl-beach-resort-spa.jpeg", description: "Bora Bora is a small South Pacific island northwest of Tahiti in French Polynesia. Surrounded by sand-fringed motus (islets) and a turquoise lagoon protected by a coral reef, it’s known for its scuba diving. It's also a popular luxury resort destination where some guest bungalows are perched over the water on stilts. At the island's center rises Mt. Otemanu, a 727m dormant volcano.")
d9 = Destination.create(location: "Old Bagan", img_url: "https://www.tripsavvy.com/thmb/gOcOe0MyJU8lgY-Zic8kdUoEBuA=/960x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-646927586-5af207593037130036dbf349.jpg", description: "Bagan is an ancient city and a UNESCO World Heritage Site located in the Mandalay Region of Myanmar. From the 9th to 13th centuries, the city was the capital of the Pagan Kingdom, the first kingdom that unified the regions that would later constitute modern Myanmar.")
d10 = Destination.create(location: "Machu Picchu", img_url: "https://cdn.tourcms.com/a/62/1810/1/large.jpg", description: "Machu Picchu is an Incan citadel set high in the Andes Mountains in Peru, above the Urubamba River valley. Built in the 15th century and later abandoned, it’s renowned for its sophisticated dry-stone walls that fuse huge blocks without the use of mortar, intriguing buildings that play on astronomical alignments and panoramic views. Its exact former use remains a mystery.")
d11 = Destination.create(location: "Bruges, Belgium", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Bruges-in-Belgium.jpg.optimal.jpg", description: "f you visit just one town in Belgium, make it Bruges. It’s one of Europe’s most beautiful fairytale towns and one of our absolute favorites. And it has nothing to do with the fact that we live in Belgium!")
d12 = Destination.create(location: "Lake Garda, Italy", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Lake-Garda-in-Italy.jpg.optimal.jpg", description: "Lake Garda is not to be missed during any Italian trip! If you like beautiful nature, quaint little villages and Italian lifestyle, you will love Lake Garda and the other Italian lakes in Northern Italy.")
d13 = Destination.create(location: " Lake Moraine, Canada", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Lake-Moraine-in-British-Columbia-Canada.jpg.optimal.jpg", description: "Moraine Lake is a glacially fed lake in Banff National Park, 14 kilometres outside the Village of Lake Louise, Alberta, Canada. It is situated in the Valley of the Ten Peaks, at an elevation of approximately 6,183 feet. The lake has a surface area of 50 hectares.")
d14 = Destination.create(location: "Arches National Park, Utah, USA", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Delicate-Arch-Arches-National-Park.jpg.optimal.jpg", description: "Arches National Park lies north of Moab in the state of Utah. Bordered by the Colorado River in the southeast, it’s known as the site of more than 2,000 natural sandstone arches, such as the massive, red-hued Delicate Arch in the east. Long, thin Landscape Arch stands in Devils Garden to the north. Other geological formations include Balanced Rock, towering over the desert landscape in the middle of the park.")
d15 = Destination.create(location: "La Digue, the Seychelles", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/La-Digue-island-in-the-Seychelles.jpg.optimal.jpg", description: "La Digue is an island in the Seychelles, in the Indian Ocean off East Africa. It’s known for its beaches, like Anse Source d’Argent, dotted with granite boulders, on the west coast. To the south, isolated Anse Bonnet Carré Beach, with calm, shallow water, is accessible only on foot, as is Anse Cocos Beach, in a protected bay on the east coast. La Digue’s diverse wildlife can be seen in the Veuve Nature Reserve.")
d16 = Destination.create(location: "Deadvlei, Namibia", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Deadvlei-Namibia.jpg.optimal.jpg", description: "Deadvlei is a white clay pan located near the more famous salt pan of Sossusvlei, inside the Namib-Naukluft Park in Namibia. Also written DeadVlei or Dead Vlei, its name means "dead marsh". The pan also is referred to as "Dooie Vlei" which is the fully Afrikaans name.")
d17 = Destination.create(location: "Hermanus, South Africa", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Hermanus-South-Africa.jpg.optimal.jpg", description: "Hermanus is a seaside town southeast of Cape Town, in South Africa’s Western Cape Province. It's known as a whale-watching destination. Beaches include Voëlklip Beach and the broad Grotto Beach, overlooking Walker Bay. The Old Harbour Museum is a site encompassing the old harbour, a fishermen’s village and the Whale House Museum. The latter has informative displays and a suspended skeleton of a whale.")
d18 = Destination.create(location: "Great Wall of China", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Great-Wall-of-China.jpg.optimal.jpg", description: "The Great Wall of China is the collective name of a series of fortification systems generally built across the historical northern borders of China to protect and consolidate territories of Chinese states and empires against various nomadic groups of the steppe and their polities.")
d19 = Destination.create(location: "Spirit Island, Canada", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Spirit-Island-on-Maligne-Lake-in-Jasper-National-Park-Canada.jpg.optimal.jpg", description: "Spirit Island is a tiny tied island in Maligne Lake in Jasper National Park. This landmark is the destination of boat trips across Maligne Lake, a view many people associate with the Canadian Rockies.")
d20 = Destination.create(location: "Rome, Italy", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Trevi-fountain-in-Rome-Italy.jpg.optimal.jpg", description: "Rome, Italy’s capital, is a sprawling, cosmopolitan city with nearly 3,000 years of globally influential art, architecture and culture on display. Ancient ruins such as the Forum and the Colosseum evoke the power of the former Roman Empire. Vatican City, headquarters of the Roman Catholic Church, has St. Peter’s Basilica and the Vatican Museums, which house masterpieces such as Michelangelo’s Sistine Chapel frescoes.")
d21 = Destination.create(location: "Jokulsarlon Glacial Lagoon, Iceland", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Jokulsarlon-Glacier-Lagoon-in-Iceland.jpg.optimal.jpg", description: "In Southeast Iceland, you'll find a glacier lagoon filled with icebergs. This ice lagoon has become one of Iceland's most popular attractions due to its stunning beauty. The lagoon is called Jökulsárlón, or 'Glacier's-River-Lagoon'.")
d22 = Destination.create(location: "Cape Cross Seal Reserve, Namibia", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Cape-Cross-seal-colony-in-Namibia.jpg.optimal.jpg", description: "Cape Cross is a small headland in the South Atlantic in Skeleton Coast, western Namibia, on the C34 highway some 60 kilometres north of Hentiesbaai and 120 km north of Swakopmund on the west coast of Namibia.")
d23 = Destination.create(location: "Maroon Bells, Colorado, USA", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Maroon-Bells-near-Aspen-Colorado-USA.jpg.optimal.jpg", description: "Maroon Bells in Colorado are said to be the most photographed mountains in the United States. No matter how many pictures you had seen, you won’t be prepared for the stunning beauty of the place. Go early in the morning to beat the crowds and see the incredible reflections on the lake. ")
d24 = Destination.create(location: "Trakai Castle, Lithuania", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Trakai-Castle-in-Lithuania.jpg.optimal.jpg", description: "Trakai Island Castle is an island castle located in Trakai, Lithuania, on an island in Lake Galvė. The construction of the stone castle was begun in the 14th century by Kęstutis, and around 1409 major works were completed by his son Vytautas the Great, who died in this castle in 1430.")
d25 = Destination.create(location: "Great Ocean Road, Southern Australia", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Great-Ocean-Road-in-Southern-Australia.jpg.optimal.jpg", description: "Great Ocean Road in Southern Australia is more than just the famous Twelve Apostles, for which more than 23 million of tourists travel to the area every year. Escape the crowds and take your time to explore the beautiful coastline beyond the most famous lookout points. There is so much you can see and do on The Great Ocean Road!")
d26 = Destination.create(location: "Grand Prismatic Spring, Yellowstone NP, USA", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Grand-Prismatic-Spring-in-Yellowstone-NP.jpg.optimal.jpg", description: "The Grand Prismatic Spring in Yellowstone National Park is everything you would expect it to be. And yes, it is as colorful as in the pictures! Yellowstone is a magical place with beautiful landscapes, incredible variety of wildlife, spurting geysers and even hot rivers… Definitely a place you should see if visiting the United States. ")
d27 = Destination.create(location: "Oeschinensee, Switzerland", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Oeschinensee-Lake-Switzerland.jpg.optimal.jpg", description: "Oeschinen Lake is a lake in the Bernese Oberland, Switzerland, 4 kilometres east of Kandersteg in the Oeschinen valley. At an elevation of 1,578 metres, it has a surface area of 1.1147 square kilometres. Its maximum depth is 56 metres. The lake is fed through a series of mountain creeks and drains underground.")
d28 = Destination.create(location: "Mont Saint-Michel Abbey, France", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Mont-Saint-Michel-in-Normandy-France.jpg.optimal.jpg", description: "The Mont Saint Michel Abbey is located within the city and island of Mont-Saint-Michel in Lower Normandy, in the department of Manche. The abbey is an essential part of the structural composition of the town the feudal society constructed.")
d29 = Destination.create(location: "Tuscany, Italy", img_url: "http://cdn2.discovertuscany.com/img/landscapes/tuscany-red-hills.jpg?auto=compress,enhance,format&w=", description: "Tuscany is a region in central Italy. Its capital, Florence, is home to some of the world’s most recognizable Renaissance art and architecture, including Michelangelo’s "David" statue, Botticelli’s works in the Uffizi Gallery and the Duomo basilica. Its diverse natural landscape encompasses the rugged Apennine Mountains, the island of Elba’s beaches on the Tyrrhenian Sea and Chianti’s olive groves and vineyards.")
d30 = Destination.create(location: "Taj Mahal, India", img_url: "https://cdn-image.travelandleisure.com/sites/default/files/styles/1600x1000/public/1514997810/taj-mahal-palace-india-VISITTAJ0118.jpg?itok=iFUqVIYN", description: "The Taj Mahal is an ivory-white marble mausoleum on the south bank of the Yamuna river in the Indian city of Agra. It was commissioned in 1632 by the Mughal emperor Shah Jahan (reigned from 1628 to 1658) to house the tomb of his favourite wife, Mumtaz Mahal; it also houses the tomb of Shah Jahan himself. The tomb is the centrepiece of a 17-hectare (42-acre) complex, which includes a mosque and a guest house, and is set in formal gardens bounded on three sides by a crenellated wall.")
d31 = Destination.create(location: "Burj Khalifa, Dubai", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Burj-Khalifa-Dubai-in-UAE.jpg.optimal.jpg", description: "The Burj Khalifa, known as the Burj Dubai prior to its inauguration in 2010, is a skyscraper in Dubai, United Arab Emirates. With a total height of 829.8 m and a roof height of 828 m, the Burj Khalifa has been the tallest structure and building in the world since its topping out in 2009.")
d32 = Destination.create(location: "Yunnan Province, China", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Lijiang-city-Jade-Spring-Park-in-Yunnan-province-in-China-.jpg.optimal.jpg", description: "Pictured is the Jade Spring Park in Lijiang city in Yunnan province in China. Yunnan province was probably the most authentic region we visited in China. Whether you are looking for natural wonders, beautiful ancient towns or incredibly diverse cultural experience, Yunnan has it all. It’s nothing like Beijing, Shanghai or other big cities, it’s real rural China and definitely not to be missed.")
d33 = Destination.create(location: "Okaukuejo Waterhole, Namibia", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Okaukuejo-waterhole-in-Etosha-National-Park-in-Namibia.jpg.optimal.jpg", description: "Why does a waterhole make it to my top destinations list? Okaukuejo in Etosha National Park is not just any waterhole; it’s like watching National Geographic channel live! Hundreds of animals come and go all day (and night) long. All you have to do is comfortably install yourself on one of the many benches and let the African wildlife come to you. It’s not the same as going on safari, of course, but it’s an incredible experience, one that is not to be missed in Namibia!")
d34 = Destination.create(location: "Bali, Indonesia", img_url: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/06/Ulan-Danu-Temple-1024x683.jpg", description: "Bali is an Indonesian island known for its forested volcanic mountains, iconic rice paddies, beaches and coral reefs. The island is home to religious sites such as cliffside Uluwatu Temple. To the south, the beachside city of Kuta has lively bars, while Seminyak, Sanur and Nusa Dua are popular resort towns. The island is also known for its yoga and meditation retreats.")
d35 = Destination.create(location: "Panorama Route, South Africa", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Panorama-Route-South-Africa.jpg.optimal.jpg", description: "The Panorama Route is a scenic road in South Africa connecting several cultural and natural points of interest. ... The route is centred around the Blyde River Canyon, the world's third largest canyon, and features numerous waterfalls, one of the largest afforested areas in South Africa, and several natural landmarks.")
d36 = Destination.create(location: "Paris", img_url: "https://europeanbusinessmagazine.com/wp-content/uploads/2017/07/paris.jpg", description: "Paris is the capital and most populous city of France, with an area of 105 square kilometres (41 square miles) and an official estimated population of 2,140,526 residents as of 1 January 2019. Since the 17th century, Paris has been one of Europe's major centres of finance, diplomacy, commerce, fashion, science, and the arts.")
d37 = Destination.create(location: "Santorini, Greece", img_url: "https://www.discovergreece.com/~/media/images/article-background-images/santorini-the-one-and-only/santorini-view.ashx", description: "Santorini is officially Thira and classic Greek Thera, is an island in the southern Aegean Sea, about 200 km (120 mi) southeast of Greece's mainland. It is the largest island of a small, circular archipelago, which bears the same name and is the remnant of a volcanic caldera.")
