# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Flight.destroy_all
User.destroy_all
Destination.destroy_all

u1 = User.create(name: "User1")

d1 = Destination.create(location: "Maya Bay, Thailand", img_url: "https://www.hawaiipublicradio.org/sites/khpr/files/styles/x_large/public/201803/maya_bay_thailand.jpg", description: "Maya Bay is a stunningly beautiful bay that's sheltered by 100-metre high cliffs on three sides. Inside the bay there are several beaches, most are small and some only exist at low tide. The main one is around 200 metres long with silky soft white sand, underwater colourful coral and exotic fish in exceptionally clear water; the whole bay is one big reef. 
Maya Bay has become the main tourist attraction of Phi Phi since The Beach was filmed here in 1999. It was always very popular before the film but now people around the world who haven't even heard of Phi Phi have certainly heard of Maya Bay. The best time to visit Maya Bay is between November and April during the high season when seas are calm and access to the bay is easy. Rough seas from May to October may hinder access but rarely deny entry. 
The bad news; as it's so beautiful and so well known many boats are required to ferry all the visitors in and out. On any given day at any time there will be 30 + speedboats and longtail boats on the beach, with large ferry boats carrying hundreds of snorkelers and sightseers moored in deeper water. Beautiful it is, secluded it isn't – thousands of people visit each day. Try to visit early in the morning or after 17:00 and you'll avoid the crowds. Please note that if you enter the bay on your own there is a National Park entry fee of 400 baht. This cost is included in the price of a tour.")

d2 = Destination.create(location: "Tokyo, Japan", img_url: "https://img.traveltriangle.com/blog/wp-content/uploads/2019/07/cover-for-Tokyo-In-October.jpg", description: "Tokyo is Japan's capital and the world's most populous metropolis. It is also one of Japan's 47 prefectures, consisting of 23 central city wards and multiple cities, towns and villages west of the city center. The Izu and Ogasawara Islands are also part of Tokyo. A beautiful mixture of traditional and modern, Tokyo is a city that will leave you awestruck. From tall skyscrapers to unique temples, you will find everything in the city. It is the place where technology meets nature and the result is commendable. And if you wish to witness the surreal side of the capital city, then visit Tokyo in October. The weather during October is simply perfect to have fun and an amazing day out. 
Prior to 1868, Tokyo was known as Edo. A small castle town in the 16th century, Edo became Japan's political center in 1603 when Tokugawa Ieyasu established his feudal government there. A few decades later, Edo had grown into one of the world's most populous cities. With the Meiji Restoration of 1868, the emperor and capital moved from Kyoto to Edo, which was renamed Tokyo. Large parts of Tokyo were destroyed in the Great Kanto Earthquake of 1923 and in the air raids of 1945.
Today, Tokyo offers a seemingly unlimited choice of shopping, entertainment, culture and dining to its visitors. The city's history can be appreciated in districts such as Asakusa and in many excellent museums, historic temples and gardens. Contrary to common perception, Tokyo also offers a number of attractive green spaces in the city center and within relatively short train rides at its outskirts.")

d3 = Destination.create(location: "Tower of London", img_url: "https://www.fodors.com/wp-content/uploads/2017/10/Ultimate-Things-To-Do-London-Tower-of-London-1-768x512.jpg", description: "With a gory 950-year history of beheadings, imprisonments, and torture, England’s most perfect medieval fortress and home of the Crown Jewels is shrouded in myth and legend. Established in 1078 by William the Conqueror, the Tower of London comprises 22 ancient towers in a fortified 18-acre site. It has been a palace, prison, and place of execution and has housed the Royal Armouries, the Royal Mint, and the Royal Menagerie. It’s still the only place you can see the 23,587 gemstones and full Coronation Regalia of the Royal Collection, including 10 dazzling crowns. 
The peak period of the castle's use as a prison was the 16th and 17th centuries, when many figures who had fallen into disgrace, such as Elizabeth I before she became queen, Sir Walter Raleigh, and Elizabeth Throckmorton, were held within its walls. This use has led to the phrase 'sent to the Tower'. Despite its enduring reputation as a place of torture and death, popularised by 16th-century religious propagandists and 19th-century writers, only seven people were executed within the Tower before the World Wars of the 20th century.
Today, the Tower of London is one of the country's most popular tourist attractions. Under the ceremonial charge of the Constable of the Tower, and operated by the Resident Governor of the Tower of London and Keeper of the Jewel House, the property is cared for by the charity Historic Royal Palaces and is protected as a World Heritage Site." )

d4 = Destination.create(location: "Venice, Italy", img_url: "https://media.tacdn.com/media/attractions-splice-spp-674x446/06/70/34/70.jpg", description: "Venice, the capital of northern Italy’s Veneto region, is built on more than 100 small islands in a lagoon in the Adriatic Sea. It has no roads, just canals – including the Grand Canal thoroughfare – lined with Renaissance and Gothic palaces. The central square, Piazza San Marco, contains St. Mark’s Basilica, which is tiled with Byzantine mosaics, and the Campanile bell tower offering views of the city’s red roofs. 
Few cities can claim such a priceless art and history heritage as Venice. This unique city with its magical, spectacular scenery is not just beautiful; it is a real miracle of creative genius: a city built on mud, sand and the slime of a difficult, inhospitable landscape.
The biggest attraction in the gorgeous city of Venice is the architecture — which is enhanced by the ancient canals that surround it. As well as Piazza San Marco and St. Mark’s Basilica, the city is home to the Gothic masterpiece Doge’s Palace. This pink and white marble buildings has to be seen in the flesh to be fully appreciated. Not only is it a breathtaking example of Italian architecture, it is also the centre of Venice Carnival celebrations every year.
If you’re looking for entertainment in Venice, you truly are spoilt for choice. Spend a few hours perusing the artworks at Museo Correr, or explore an exciting mix of Renaissance and modern art at Punta della Dogana.")

d5 = Destination.create(location: "Cape Town, South Africa" , img_url: "https://media.timeout.com/images/105237728/image.jpg", description: "Cape Town is a legislative capital of South Africa, colloquially named the Mother City. It forms part of the City of Cape Town metropolitan municipality. 
It sits on a peninsula beneath the imposing Table Mountain. Slowly rotating cable cars climb to the mountain’s flat top, from which there are sweeping views of the city, the busy harbor and boats heading for Robben Island, the notorious prison that once held Nelson Mandela, which is now a living museum.
It is one of the most multicultural cities in the world, reflecting its role as a major destination for immigrants and expatriates to South Africa. The city was named the World Design Capital for 2014 by the International Council of Societies of Industrial Design. In 2014, Cape Town was named the best place in the world to visit by both The New York Times and The Daily Telegraph.
Cape Town outgrew its original purpose as the first European outpost at the Castle of Good Hope, becoming the economic and cultural hub of the Cape Colony. Until the Witwatersrand Gold Rush and the development of Johannesburg, Cape Town was the largest city in South Africa.")

d6 = Destination.create(location: "Marrakesh, Morocco", img_url: "https://www.planetware.com/wpimages/2019/04/morocco-marrakesh-top-attractions-marrakesh-tanneries.jpg", description: "Marrakesh, a former imperial city in western Morocco, is a major economic center and home to mosques, palaces and gardens. The Medina is a densely packed, walled medieval city dating to the Berber Empire, with mazelike alleys where thriving souks (marketplaces) sell traditional textiles, pottery and jewelry. A symbol of the city, and visible for miles, is the Moorish minaret of 12th-century Koutoubia Mosque.
Marrakesh is possibly the second most important of Morocco's four former imperial cities after Fez. The region has been inhabited by Berber farmers since Neolithic times, but the actual city was founded in 1062, by Abu Bakr ibn Umar, chieftain and cousin of Almoravid king Yusuf ibn Tashfin. In the 12th century, the Almoravids built many madrasas (Koranic schools) and mosques in Marrakesh that bear Andalusian influences. The red walls of the city, built by Ali ibn Yusuf in 1122–1123, and various buildings constructed in red sandstone during this period, have given the city the nickname of the 'Red City' or 'Ochre City'. Marrakesh grew rapidly and established itself as a cultural, religious, and trading center for the Maghreb and sub-Saharan Africa; Jemaa el-Fnaa is the busiest square in Africa.
Marrakesh is served by Ménara International Airport and the Marrakesh railway station, which connects the city to Casablanca and northern Morocco. Marrakesh has several universities and schools, including Cadi Ayyad University. A number of Moroccan football clubs are located here, including Najm de Marrakech, KAC Marrakech, Mouloudia de Marrakech and Chez Ali Club de Marrakech. The Marrakesh Street Circuit hosts the World Touring Car Championship, Auto GP and FIA Formula Two Championship races.")

d7 = Destination.create(location: "Milford Sound, New Zealand", img_url: "https://www.newzealand.com/assets/Tourism-NZ/Fiordland/1981c26c52/img-1536158664-5812-17824-722C5D30-9984-DC99-AF48D13DBA41C21E-v2__FocalPointCropWzQyNyw2NDAsNTUsNTAsODUsImpwZyIsNjUsMi41XQ.jpg", description: "Milford Sound is a fiord in the southwest of New Zealand’s South Island. It’s known for towering Mitre Peak, plus rainforests and waterfalls like Stirling and Bowen falls, which plummet down its sheer sides. The fiord is home to fur seal colonies, penguins and dolphins. Milford Discovery Centre and Underwater Observatory offers views of rare black coral and other marine life. Boat tours are a popular way to explore.
Described by Rudyard Kipling as the 'eighth wonder of the world', Milford Sound was carved by glaciers during the ice ages. Breathtaking in any weather, the fiord's cliffs rise vertically from the dark waters, mountain peaks scrape the sky and waterfalls cascade downwards from as high as 1000 metres. When it rains in Milford Sound, and it often does, those waterfalls multiply with magnificent effect. 
Boat cruises – during the day or overnight – are an excellent way to experience the Sound. Adventurous types might also like to head out sea kayaking, diving or flightseeing. To learn more about the local marine life, visit the underwater observatory at Harrison Cove and marvel at the black coral, 11-legged sea stars and delicate anemones.")

d8 = Destination.create(location: "Bora Bora,  French Polynesia", img_url: "https://dbijapkm3o6fj.cloudfront.net/resources/1608,1004,1,6,4,0,960,540/-4153-/20190810121416/stay-minimum-3-nights-save-25-with-breakfast-included-bora-bora-pearl-beach-resort-spa.jpeg", description: "Bora Bora is a small South Pacific island northwest of Tahiti in French Polynesia. Surrounded by sand-fringed motus (islets) and a turquoise lagoon protected by a coral reef, it’s known for its scuba diving. It's also a popular luxury resort destination where some guest bungalows are perched over the water on stilts. At the island's center rises Mt. Otemanu, a 727m dormant volcano.
Bora Bora rises from the velvet blues of the deep water up through the softer hues of the lagoon and into the air that surrounds the island. Its touch on the sea breeze tingles the skin. And its power fills each beat of the heart. Bora Bora is located a brief 50-minute flight from The Islands of Tahiti or Moorea, Bora Bora, with a lagoon resembling an artist’s palette of bright blues and greens, is love at first sight. Romantics from around the world celebrate Bora Bora where the lush tropical slopes and valleys of Mount Otemanu blossom with hibiscus, while palm-covered motu circle the illuminated lagoon like a delicate necklace.
The perfect white-sand Bora Bora beaches give way to blue waters where tropical-colored fish animate the coral gardens and giant manta rays glide leisurely past. This could easily be defined as the center of the romantic universe, where luxury resorts and spas dot the island with overwater bungalows, thatched-roof villas, and a fabled ambiance. Simply put, Bora Bora is one of the most beautiful islands in the world.")

d9 = Destination.create(location: "Old Bagan, Myanmar", img_url: "https://www.tripsavvy.com/thmb/gOcOe0MyJU8lgY-Zic8kdUoEBuA=/960x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-646927586-5af207593037130036dbf349.jpg", description: "Bagan is an ancient city and a UNESCO World Heritage Site located in the Mandalay Region of Myanmar. From the 9th to 13th centuries, the city was the capital of the Pagan Kingdom, the first kingdom that unified the regions that would later constitute modern Myanmar.
Bagan, located on the banks of the Ayeyarwady (Irrawaddy) River, is home to the largest and densest concentration of Buddhist temples, pagodas, stupas and ruins in the world with many dating from the 11th and 12th centuries. The shape and construction of each building is highly significant in Buddhism with each component part taking on spiritual meaning.
The area’s most active town and main transport hub is Nyaung U, in the northeastern corner. About 2.5 miles west, Old Bagan is the former site of the village that was relocated 2 miles south to New Bagan in 1990. Between the two is Myinkaba, a village boasting a long-running lacquerware tradition.
Bagan has been hit by earthquakes over the centuries. The most recent, in August 2016, damaged 400 temples; work on repairing them is ongoing. Bear in mind that Bagan is not a traveller destination with nightlife like Siem Reap (Cambodia) or even Luang Prabang (Laos). It's an overgrown village, so party elsewhere.")

d10 = Destination.create(location: "Machu Picchu, Peru", img_url: "https://cdn.tourcms.com/a/62/1810/1/large.jpg", description: "Machu Picchu is an Incan citadel set high in the Andes Mountains in Peru, above the Urubamba River valley. Built in the 15th century and later abandoned, it’s renowned for its sophisticated dry-stone walls that fuse huge blocks without the use of mortar, intriguing buildings that play on astronomical alignments and panoramic views. Its exact former use remains a mystery.
These remarkable ruins became known to the scientific world in 1911, after the American archaeologist Hiram Bingham was led to the site by locals. Perched dramatically 1000 feet above the Urubamba river, Machu Picchu is a UNESCO World Heritage List|UNESCO World Heritage site. It is also the end point of the most popular hikes in South America, the Inca Trail.
The story of Machu Picchu is quite a remarkable one; it is still unknown exactly what the site was in terms of its place in Inca life. Current researchers tend to believe that Machu Picchu was a country resort for elite Incas. At any given time, there were no more than 750 people living at Machu Picchu, with far fewer than that during the rainy season. The Incas started building it around 1430AD, but it was abandoned as an official site for the Inca rulers a hundred years later at the time of the Spanish conquest of the Inca Empire.
One thing that is clear is that it was a remarkably well hidden place, and well protected. Located far up in the mountains of Peru, visitors had to travel up long valleys littered with Inca check points and watch towers. Remarkably, the Spanish conquistadors missed the site. However, many people are said to have knowledge of the ancient city as it was referred to in some text found in the 20th century; even so, it was not until Bingham that Machu Picchu was scientifically discovered (he was on a trip sponsored by the Yale University, actually looking for Vilcabamba, the last Inca hideout).")

d11 = Destination.create(location: "Bruges, Belgium", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Bruges-in-Belgium.jpg.optimal.jpg", description: "f you visit just one town in Belgium, make it Bruges. It’s one of Europe’s most beautiful fairytale towns. Relatively cosmopolitan and bourgeois given its compact size, it is one of the best preserved pre-motorised cities in Europe and offers the kind of charms rarely available elsewhere. Bruges is a postcard perfect stop on any tour of Europe.
Once over the encircling canal and inside the city walls, Bruges closes in around you with street after street of charming historic houses and a canal always nearby. In recent years, the city has turned so much towards tourism the locals sometimes complain they are living in Disney-land. The newly cleaned houses should however not confuse you; they are truly centuries old. And if you can get away from the chocolate-shops, you can visit some more quiet areas s.a. St. Anna, and imagine what life in the late middle ages must have been like.
It is also possible to buy a combined ticket to see all Musea Brugge museums, which is good value if you intend to visit more than 2.
Several Youth Hostels (Bauhaus), and probably the train station and tourist information, offer a useful map with some very interesting, 'non-tourist' places to see during the day and some unique places to visit at night. It provides a good way of getting an authentic feel for the town whilst avoiding the tourist honey-pots and allows you to find some hidden gems.")

d12 = Destination.create(location: "Lake Garda, Italy", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Lake-Garda-in-Italy.jpg.optimal.jpg", description: "Lake Garda is not to be missed during any Italian trip! If you like beautiful nature, quaint little villages and Italian lifestyle, you will love Lake Garda and the other Italian lakes in Northern Italy.
There are many historical places and buildings around the lake. The architectural style is mostly traditional Italian vernacular, which is very picturesque. There are also many classical style building churches, grand houses and castles. There is a large church located at the northernmost end of the lake, but appropriate clothing must be worn when visiting (eg. knees and shoulders must not be showing). The town of Limone gets its name from... guess what... lemons! Lemon trees grow throughout it, and is a lovely view.
As per usual, fine Italian cuisine is sold. This consists of pasta, pizza and many other traditional Italian dishes. But other options are available such as German, American and British style foods. Italian ice-cream is fresh and homemade- great for those who have a sweethtooth. Ice-cream shops are common, with some sprouting out of shops and restaurants. Some 'gelato' (ice-cream-like treat usually made in the shop) shops have 50+ flavours. Smaller shops with only a half dozen flavors might be more enjoyable. These seem to focus on the flavors they offer,and making the decision on which flavour to choose will take much less time. Breakfast is not the same as English or American breakfasts so be careful when you ask for full board. Breakfast at Le Paul in Sirmione, has English and American style foods. They even offer cereal.")

d13 = Destination.create(location: "Lake Moraine, Canada", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Lake-Moraine-in-British-Columbia-Canada.jpg.optimal.jpg", description: "Moraine Lake is a glacially fed lake in Banff National Park, 14 kilometres outside the Village of Lake Louise, Alberta, Canada. It is situated in the Valley of the Ten Peaks, at an elevation of approximately 6,183 feet. The lake has a surface area of 50 hectares.
The lake, being glacially fed, does not reach its crest until mid to late June. When it is full, it reflects a distinctive shade of azure blue. The unique colour is due to the refraction of light off the rock flour deposited in the lake on a continual basis by surrounding glaciers.
The area around the lake has several walking/hiking trails which are, from time to time, restricted. The trail most commonly taken by tourists is The Rockpile Trail, which is along the actual moraine. The trail is approximately 300 metres (980 ft) long, with an elevation change of 24 metres (79 ft). The view of the lake from the top of the rockpile is one of the most photographed locations in all of Canada.[1]That view of the mountains behind the lake in Valley of the Ten Peaks is known as the 'Twenty Dollar View', as Moraine Lake was featured on the reverse side of the 1969 and 1979 issues of the Canadian twenty dollar bill.")

d14 = Destination.create(location: "Arches National Park, Utah, USA", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Delicate-Arch-Arches-National-Park.jpg.optimal.jpg", description: "Arches National Park lies north of Moab in the state of Utah. Bordered by the Colorado River in the southeast, it’s known as the site of more than 2,000 natural sandstone arches, such as the massive, red-hued Delicate Arch in the east. Long, thin Landscape Arch stands in Devils Garden to the north. Other geological formations include Balanced Rock,towering over the desert landscape in the middle of the park.
The national park lies above an underground evaporite layer or salt bed, which is the main cause of the formation of the arches, spires, balanced rocks, sandstone fins, and eroded monoliths in the area. This salt bed is thousands of feet thick in places, and was deposited in the Paradox Basin of the Colorado Plateau some 300 million years ago (Mya) when a sea flowed into the region and eventually evaporated. Over millions of years, the salt bed was covered with debris eroded from the Uncompahgre Uplift to the northeast. 
Although the park's terrain may appear rugged and durable, it is extremely fragile. More than 1 million visitors each year threaten the fragile high-desert ecosystem.[8] The problem lies within the soil's crust, which is composed of cyanobacteria, algae, fungi, and lichens that grow in the dusty parts of the park. Factors that make Arches National Park sensitive to visitor damage include being a semiarid region,the scarce, unpredictable rainfall, lack of deep freezing, and lack of plant litter, which results in soils that have both a low resistance to, and slow recovery from, compressional forces such as foot traffic.")

d15 = Destination.create(location: "La Digue, the Seychelles", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/La-Digue-island-in-the-Seychelles.jpg.optimal.jpg", description: "La Digue is an island in the Seychelles, in the Indian Ocean off East Africa. It’s known for its beaches, like Anse Source d’Argent, dotted with granite boulders, on the west coast. To the south, isolated Anse Bonnet Carré Beach, with calm, shallow water, is accessible only on foot, as is Anse Cocos Beach, in a protected bay on the east coast. La Digue’s diverse wildlife can be seen in the Veuve Nature Reserve.
According to modern historians, La Digue was first sighted by the French navigator Lazare Picault in 1742, but it was not named until 1768. The first people settled on the island in 1789, when French colonists arrived with their African slaves. Most of them went back to France, but some people were left and some of today's inhabitants carry their names. Later, more French deportees arrived, followed by a large number of liberated slaves and Asian immigrants.
Since La Digue is an island inhabited by many ethnic groups, the cuisine is a specific mix of world cuisines. With the abundance of fish, the Seychellois people have learned how to make hundreds of recipes out of this simple ingredient. One can have fish curry, fish fillets, raw fish with lemon, grilled fish, steamed fish, cooked fish and so on. The inhabitants of La Digue also make fried octopus, lobster with garlic and their biggest speciality – bat curry. An ingredient used to a very large degree is ginger, which is put in many meals. The most popular alcoholic drink on La Digue is palm wine, which most Seychellois people like to make themselves by fermenting the inside of a coconut.")

d16 = Destination.create(location: "Deadvlei, Namibia", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Deadvlei-Namibia.jpg.optimal.jpg", description: "Deadvlei is a white clay pan located near the more famous salt pan of Sossusvlei, inside the Namib-Naukluft Park in Namibia. Also written DeadVlei or Dead Vlei (its name means dead marsh). The pan also is referred to as 'Dooie Vlei' which is the fully Afrikaans name.
Dead Vlei has been claimed to be surrounded by the highest sand dunes in the world, the highest reaching 300–400 meters (350m on average, named 'Big Daddy' or 'Crazy Dune'), which rest on a sandstone terrace.
The clay pan was formed after rainfall, when the Tsauchab river flooded, creating temporary shallow pools where the abundance of water allowed camel thorn trees to grow. When the climate changed, drought hit the area, and sand dunes encroached on the pan, which blocked the river from the area.
The trees died, as there no longer was enough water to survive. There are some species of plants remaining, such as salsola and clumps of nara, adapted to surviving off the morning mist and very rare rainfall. The remaining skeletons of the trees, which are believed to have died 600–700 years ago (ca. 1340-1430), are now black because the intense sun has scorched them. Though not petrified, the wood does not decompose because it is so dry.
Films partly shot there include The Cell (starring Jennifer Lopez), The Fall, and Ghajini.")

d17 = Destination.create(location: "Hermanus, South Africa", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Hermanus-South-Africa.jpg.optimal.jpg", description: "Hermanus is a seaside town southeast of Cape Town, in South Africa’s Western Cape Province. It's known as a whale-watching destination. Beaches include Voëlklip Beach and the broad Grotto Beach, overlooking Walker Bay. The Old Harbour Museum is a site encompassing the old harbour, a fishermen’s village and the Whale House Museum. The latter has informative displays and a suspended skeleton of a whale.
Hermanus hosts an annual whale festival at the end of September, to celebrate the calving and mating season. Eco-Tourism is the main theme of the Hermanus whale festival with the Eco-Marine Village. Residents and visitors celebrate the migration of Southern Right Whales and other marine wildlife with ocean-themed activities and exhibitions, emphasising education and environmentally responsible adventures and activities. Prior to this main whale festival a Kalfiefees (or Calf Festival) is held, to welcome the first whales (usually in August). Both festivals are characterised by food and craft stalls, environmental presentations and South African drama productions.")

d18 = Destination.create(location: "Great Wall of China", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Great-Wall-of-China.jpg.optimal.jpg", description: "The Great Wall of China is the collective name of a series of fortification systems generally built across the historical northern borders of China to protect and consolidate territories of Chinese states and empires against various nomadic groups of the steppe and their polities.
Several walls were being built from as early as the 7th century BC by ancient Chinese states; selective stretches were later joined together by Qin Shi Huang (220–206 BC), the first Emperor of China. Little of the Qin wall remains. Later on, many successive dynasties have built and maintained multiple stretches of border walls. The most well-known sections of the wall were built by the Ming dynasty (1368–1644).
Apart from defense, other purposes of the Great Wall have included border controls, allowing the imposition of duties on goods transported along the Silk Road, regulation or encouragement of trade and the control of immigration and emigration. Furthermore, the defensive characteristics of the Great Wall were enhanced by the construction of watch towers, troop barracks, garrison stations, signaling capabilities through the means of smoke or fire, and the fact that the path of the Great Wall also served as a transportation corridor.")

d19 = Destination.create(location: "Spirit Island, Canada", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Spirit-Island-on-Maligne-Lake-in-Jasper-National-Park-Canada.jpg.optimal.jpg", description: "Spirit Island is a tiny tied island in Maligne Lake in Jasper National Park. This landmark is the destination of boat trips across Maligne Lake, a view many people associate with the Canadian Rockies.
In spring, with melting snow and heavy rains, it’s possible for the water levels to be high enough to cut the island off from the shore. The rest of the year, it’s connected to shore. Spirit Island sits in the heart of what's called a 'box canyon'—a narrow canyon with a flat bottom and vertical walls.
The island is a spiritual place for the Stoney Nakoda First Nation, who believe mountains are physical representations of their ancestors. The fact that Spirit Island is surrounded on three sides by the same mountain range is very rare and makes it particularly significant to the Stoney.
Access to the island is extremely limited due to its geography. It's in on a remote shore in a cold lake surrounded by high peaks and glacier, 14 km from the docks at Home Bay. It's hard to get to—paddling on your own can take four hours each way! ")

d20 = Destination.create(location: "Rome, Italy", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Trevi-fountain-in-Rome-Italy.jpg.optimal.jpg", description: "Rome, Italy’s capital, is a sprawling, cosmopolitan city with nearly 3,000 years of globally influential art, architecture and culture on display. Ancient ruins such as the Forum and the Colosseum evoke the power of the former Roman Empire. Vatican City, headquarters of the Roman Catholic Church, has St. Peter’s Basilica and the Vatican Museums, which house masterpieces such as Michelangelo’s Sistine Chapel frescoes.
Rome is located in the central-western portion of the Italian Peninsula, within Lazio (Latium), along the shores of the Tiber. The Vatican City (the smallest country in the world) is an independent country inside the city boundaries of Rome, the only existing example of a country within a city: for this reason Rome has been often defined as capital of two states.
Rome's history spans 28 centuries. While Roman mythology dates the founding of Rome at around 753 BC, the site has been inhabited for much longer, making it one of the oldest continuously occupied sites in Europe.[6] The city's early population originated from a mix of Latins, Etruscans, and Sabines. Eventually, the city successively became the capital of the Roman Kingdom, the Roman Republic and the Roman Empire, and is regarded by some as the first ever metropolis.")

d23 = Destination.create(location: "Maroon Bells, Colorado, USA", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Maroon-Bells-near-Aspen-Colorado-USA.jpg.optimal.jpg", description: "A reflective lake and two giant snow-striped mountaintops, named Maroon Peak and North Maroon Peak, anchor a blissful panorama exemplified by a symphony of color that changes with the seasons.
Located just 10 miles west of Aspen or 16 from Snowmass up Maroon Creek Road off Hwy. 82 in a glacial valley, the 14,000-foot peaks (fourteeners) truly epitomize the beauty of the Rocky Mountains. Hiking trails provide access to plenty of photo-worthy scenes in the White River National Forest, including hypnotizing wildflower fields, fly-fishermen seeking catches in tranquil Maroon Lake and brilliant fall colors on aspen trees.
More than 300 million years of geologic activity, including sedimentation, uplift and erosion by wind, water and ice, are credited to the creation of Maroon Valley. According to the US Forest Service, the mountains received their distinctive maroon coloring from the weathering of hematite, an iron-bearing mineral, while Maroon Lake occupies a basin that was sculpted by Ice-Age glaciers.")

d21 = Destination.create(location: "Jokulsarlon Glacial Lagoon, Iceland", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Jokulsarlon-Glacier-Lagoon-in-Iceland.jpg.optimal.jpg", description: "In Southeast Iceland, you'll find a glacier lagoon filled with icebergs. This ice lagoon has become one of Iceland's most popular attractions due to its stunning beauty. The lagoon is called Jökulsárlón, or 'Glacier's-River-Lagoon'.
Jökulsárlón sits south of Vatnajökull, Europe's largest glacier. Vatnajökull and its surrounding area, including Jökulsárlón, compose Iceland's largest national park, and the second largest national park in Europe, after Yugid Va in Russia.
The lagoon is formed naturally from melted glacial water and is perpetually growing while big blocks of ice crumble from the ever-shrinking glacier; as Jökulsárlón increases in size, the retreating glacier visibly demonstrates the effects of global warming.
This, perhaps, makes the lagoon and the nearby glacier tongue even more special, as they will look different each time you pay them a visit.
The icebergs that break away from the glacier and fall into the lagoon, slowly melt and drift out to sea, where they are polished by the North Atlantic waves before being washed ashore on the jet-black beach called Breiðamerkursandur.")

d22 = Destination.create(location: "Cape Cross Seal Reserve, Namibia", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Cape-Cross-seal-colony-in-Namibia.jpg.optimal.jpg", description: "Cape Cross is a small headland in the South Atlantic in Skeleton Coast, western Namibia, on the C34 highway some 60 kilometres north of Hentiesbaai and 120 km north of Swakopmund on the west coast of Namibia.
Today Cape Cross is a protected area owned by the government of Namibia under the name Cape Cross Seal Reserve. The reserve is the home of one of the largest colonies of Cape fur seals in the world.
Cape Cross is one of two main sites in Namibia (the other is in Lüderitz) where seals are culled, partly for selling their hides and partly for protecting the fish stock. The economic impact of seals on the fish resources is controversial: While a government-initiated study found that seal colonies consume more fish than the entire fishing industry can catch, animal protection society Seal Alert South Africa estimated less than 0.3% losses to commercial fisheries.")

d24 = Destination.create(location: "Trakai Castle, Lithuania", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Trakai-Castle-in-Lithuania.jpg.optimal.jpg", description: "Trakai Island Castle is an island castle located in Trakai, Lithuania, on an island in Lake Galvė. The construction of the stone castle was begun in the 14th century by Kęstutis, and around 1409 major works were completed by his son Vytautas the Great, who died in this castle in 1430. Trakai was one of the main centers of the Grand Duchy of Lithuania and the castle held great strategic importance.
Trakai Island Castle lost its military importance soon after the Battle of Grunwald, when the chief enemy of the Grand Duchy of Lithuania was defeated by the Lithuanian-Polish army. The castle was transformed into a residence and newly decorated from the inside. New frescos were painted on its walls, which have been partially preserved. Foreign emissaries were welcomed in the Ducal Palace. It is known that Jogaila visited the castle thirteen times between 1413 and 1430. In 1414, the Flemish traveler Guillebert de Lannoy described the castle in these words:
The old castle stands on one side of the lake, in open ground, the another one stands in the middle of a second lake, and is within a cannon shot of the old one. It is completely new, built from bricks following French pattern.")

d25 = Destination.create(location: "Great Ocean Road, Southern Australia", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Great-Ocean-Road-in-Southern-Australia.jpg.optimal.jpg", description: "The Great Ocean Road is an Australian National Heritage listed 243-kilometre (151 mi) stretch of road along the south-eastern coast of Australia between the Victorian cities of Torquay and Allansford. Built by returned soldiers between 1919 and 1932 and dedicated to soldiers killed during World War I, the road is the world's largest war memorial. Winding through varying terrain along the coast and providing access to several prominent landmarks, including the Twelve Apostles limestone stack formations, the road is an important tourist attraction in the region.
The Great Ocean Road starts at Torquay and travels 243 kilometres westward to finish at Allansford near Warrnambool, the largest city along the road. The road is two lanes (one in each direction), and is covered by a speed limit changing between 50 kilometres per hour and 100 kilometres per hour.
The road is considered a tourist attraction in the area, in which much of the road hugs coastline affectionately known as the Surf Coast, between Torquay and Cape Otway, and the Shipwreck Coast further west of Cape Otway, providing visibility of Bass Strait and the Southern Ocean. The road traverses rainforests, as well as beaches and cliffs composed of limestone and sandstone, which is susceptible to erosion.")

d26 = Destination.create(location: "Grand Prismatic Spring, Yellowstone NP, USA", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Grand-Prismatic-Spring-in-Yellowstone-NP.jpg.optimal.jpg", description: "The Grand Prismatic Spring in Yellowstone National Park is the largest hot spring in the United States, and the third largest in the world, after Frying Pan Lake in New Zealand and Boiling Lake in Dominica. It is located in the Midway Geyser Basin.
Grand Prismatic Spring was noted by geologists working in the Hayden Geological Survey of 1871, and named by them for its striking coloration. Its colors match most of those seen in the rainbow dispersion of white light by an optical prism: red, orange, yellow, green, and blue.
The vivid colors in the spring are the result of microbial mats around the edges of the mineral-rich water. The mats produce colors ranging from green to red; the amount of color in the microbial mats depends on the ratio of chlorophyll to carotenoids and on the temperature gradient in the runoff. In the summer, the mats tend to be orange and red, whereas in the winter the mats are usually dark green. The center of the pool is sterile due to extreme heat.
The deep blue color of the water in the center of the pool results from the intrinsic blue color of water. The effect is strongest in the center of the spring, because of its sterility and depth.
The Grand Prismatic Spring in Yellowstone National Park is everything you would expect it to be. And yes, it is as colorful as in the pictures! Yellowstone is a magical place with beautiful landscapes, incredible variety of wildlife, spurting geysers and even hot rivers… Definitely a place you should see if visiting the United States. ")

d27 = Destination.create(location: "Oeschinensee, Switzerland", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Oeschinensee-Lake-Switzerland.jpg.optimal.jpg", description: "Oeschinen Lake is a lake in the Bernese Oberland, Switzerland, 4 kilometres east of Kandersteg in the Oeschinen valley. At an elevation of 1,578 metres, it has a surface area of 1.1147 square kilometres. Its maximum depth is 56 metres. The lake is fed through a series of mountain creeks and drains underground.
The water then resurfaces as the Oeschibach. Part of it is captured for electricity production and as water supply for Kandersteg.
In observations from 1931 to 1965, the elevation of the lake surface varied between 1,566.09 metres (5,138.1 ft) and 1,581.9 metres (5,190 ft). The average seasonal variation was 12.2 metres (40 ft) (September/April).
The lake is generally frozen during five months, from December to May. From time to time ice skating is possible on the ice.
Fish in the lake include Arctic char (Seesaibling), lake trout (Kanadische Seeforelle), rainbow trout (Regenbogenforelle). From January to March, ice fishing is popular. A gondola lift from Kandersteg leads to Oeschinen, 25 minutes by foot from the lake.
Since 2007 the lake is part of the Jungfrau-Aletsch-Bietschhorn UNESCO World Heritage Site.")

d28 = Destination.create(location: "Mont Saint-Michel Abbey, France", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Mont-Saint-Michel-in-Normandy-France.jpg.optimal.jpg", description: "The Mont Saint Michel Abbey is located within the city and island of Mont-Saint-Michel in Lower Normandy, in the department of Manche. The abbey is an essential part of the structural composition of the town the feudal society constructed.
The abbey has been protected as a French monument historique since 1862. Since 1979, the site as a whole – i.e., the Mont Saint-Michel and its bay – has been a UNESCO world heritage site and is managed by the Centre des monuments nationaux.
With more than 1.335 million visitors in 2010, the abbey is among the most visited cultural sites in France.")

d29 = Destination.create(location: "Tuscany, Italy", img_url: "http://cdn2.discovertuscany.com/img/landscapes/tuscany-red-hills.jpg?auto=compress,enhance,format&w=", description: "Tuscany is a region in central Italy. It is known for its landscapes, history, artistic legacy, and its influence on high culture. It is regarded as the birthplace of the Italian Renaissance and has been home to many figures influential in the history of art and science, and contains well-known museums such as the Uffizi and the Pitti Palace. Tuscany produces wines, including Chianti, Vino Nobile di Montepulciano, Morellino di Scansano and Brunello di Montalcino. Having a strong linguistic and cultural identity, it is sometimes considered a 'nation within a nation'.
Tuscany is a popular destination in Italy; the main tourist spots are Florence, Pisa, Lucca, Siena, Versilia, Maremma and Chianti.[6] The village of Castiglione della Pescaia is the most visited seaside destination in the region, with seaside tourism accounting for approximately 40% of tourist arrivals. Additionally, Siena, Lucca, the Chianti region, Versilia and Val d'Orcia are also internationally renowned and particularly popular spots among travellers.
Seven Tuscan localities have been designated World Heritage Sites: the historic centre of Florence (1982); the Cathedral square of Pisa (1987); the historical centre of San Gimignano (1990); the historical centre of Siena (1995); the historical centre of Pienza (1996); the Val d'Orcia (2004), and the Medici Villas and Gardens (2013). Tuscany has over 120 protected nature reserves, making Tuscany and its capital Florence popular tourist destinations that attract millions of tourists every year. In 2012, the city of Florence was the world's 89th most visited city, with 1.834 million arrivals.")

d30 = Destination.create(location: "Taj Mahal, India", img_url: "https://cdn-image.travelandleisure.com/sites/default/files/styles/1600x1000/public/1514997810/taj-mahal-palace-india-VISITTAJ0118.jpg?itok=iFUqVIYN", description: "The Taj Mahal is an ivory-white marble mausoleum on the south bank of the Yamuna river in the Indian city of Agra. It was commissioned in 1632 by the Mughal emperor Shah Jahan (reigned from 1628 to 1658) to house the tomb of his favourite wife, Mumtaz Mahal; it also houses the tomb of Shah Jahan himself. The tomb is the centrepiece of a 17-hectare (42-acre) complex, which includes a mosque and a guest house, and is set in formal gardens bounded on three sides by a crenellated wall.
Construction of the mausoleum was essentially completed in 1643, but work continued on other phases of the project for another 10 years. The Taj Mahal complex is believed to have been completed in its entirety in 1653 at a cost estimated at the time to be around 32 million rupees, which in 2015 would be approximately 52.8 billion rupees (U.S. $827 million). The construction project employed some 20,000 artisans under the guidance of a board of architects led by the court architect to the emperor, Ustad Ahmad Lahauri.
The Taj Mahal was designated as a UNESCO World Heritage Site in 1983 for being 'the jewel of Muslim art in India and one of the universally admired masterpieces of the world's heritage'. It is regarded by many as the best example of Mughal architecture and a symbol of India's rich history. The Taj Mahal attracts 7–8 million visitors a year and in 2007, it was declared a winner of the New7Wonders of the World (2000–2007) initiative.")

d31 = Destination.create(location: "Burj Khalifa, Dubai", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Burj-Khalifa-Dubai-in-UAE.jpg.optimal.jpg", description: "The Burj Khalifa, known as the Burj Dubai prior to its inauguration in 2010, is a skyscraper in Dubai, United Arab Emirates. With a total height of 829.8 m and a roof height of 828 m, the Burj Khalifa has been the tallest structure and building in the world since its topping out in 2009.
Construction of the Burj Khalifa began in 2004, with the exterior completed five years later in 2009. The primary structure is reinforced concrete. The building was opened in 2010 as part of a new development called Downtown Dubai. It is designed to be the centrepiece of large-scale, mixed-use development. The decision to construct the building is based on the government's decision to diversify from an oil-based economy, and for Dubai to gain international recognition. The building was originally named Burj Dubai but was renamed in honour of the ruler of Abu Dhabi and president of the United Arab Emirates, Khalifa bin Zayed Al Nahyan; Abu Dhabi and the UAE government lent Dubai money to pay its debts. The building broke numerous height records, including its designation as the tallest building in the world.")

d32 = Destination.create(location: "Yunnan Province, China", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Lijiang-city-Jade-Spring-Park-in-Yunnan-province-in-China-.jpg.optimal.jpg", description: "Yunnan is the most diverse province in all China, both in its extraordinary mix of peoples and in the splendour of its landscapes. That combination of superlative sights and many different ethnic groups has made Yunnan the trendiest destination for China’s exploding domestic tourist industry.
More than half of the country’s minority groups reside here, providing a glimpse into China’s hugely varied mix of humanity. Then there’s the eye-catching contrasts of the land itself: dense jungle sliced by the Mekong River in the far south; soul-recharging glimpses of the sunset over rice terraces in the southeastern regions; snowcapped mountains as you edge towards Tibet.
Infrastructure development makes travel here easier than ever, but you’ll need time to see it all – whatever time you’ve set aside for Yunnan, double it.")

d33 = Destination.create(location: "Okaukuejo Waterhole, Namibia", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Okaukuejo-waterhole-in-Etosha-National-Park-in-Namibia.jpg.optimal.jpg", description: "Famous for its floodlit waterhole Okaukuejo Rest Camp is also the administrative centre of Etosha. Most visitors travel though this camp with its characteristic stone tower and Etosha Ecological Institute is also situated within the camp.
The rest camp was formerly a military outpost founded in 1901 and the tower was added in 1963. Located in the south of Etosha National Park, Okaukuejo is only 17 km from Anderson Gate. Okaukuejo offers a wide range of accommodation as well as all the necessities such as a petrol station and a shop. The restaurant and bar offer refreshments and delicious meals, while the swimming pool offers relief on hot days. The waterhole is a hub of animal activity starting in the early hours of the morning. Especially during winter diversity of game congregate in close proximity to the camp to quench their thirst.
After sunset floodlights illuminate the waterhole. This is the best time and place to see the endangered black rhino. This archaic mammal can often be seen drinking alongside lion and elephant. The number and interaction of the animals is the major drawcard of Okaukuejo Rest Camp in Namibia.")

d34 = Destination.create(location: "Bali, Indonesia", img_url: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/06/Ulan-Danu-Temple-1024x683.jpg", description: "Bali is an Indonesian island known for its forested volcanic mountains, iconic rice paddies, beaches and coral reefs. The island is home to religious sites such as cliffside Uluwatu Temple. To the south, the beachside city of Kuta has lively bars, while Seminyak, Sanur and Nusa Dua are popular resort towns. The island is also known for its yoga and meditation retreats.
The rich and diverse culture of Bali plays out at all levels of life, from the exquisite flower-petal offerings placed everywhere, to the processions of joyfully garbed locals shutting down major roads as they march to one of the myriad temple ceremonies, to the otherworldly traditional music and dance performed island-wide. Almost everything has spiritual meaning. The middle of Bali is dominated by the dramatic volcanoes of the central mountains and hillside temples such as Pura Luhur Batukau, one of the island's estimated 10,000 temples, while the tallest peak, Gunung Agung, is the island's spiritual centre.
Yes, Bali has beaches, surfing, diving and resorts great and small, but it's the essence of Bali – and the Balinese – that makes it so much more than just a fun-in-the-sun retreat. It is possible to take the cliché of the smiling Balinese too far, but in reality, the inhabitants of this small island are indeed a generous, genuinely warm people. There's also a fun, sly sense of humour. Upon seeing a bald tourist, many locals exclaim 'bung ujan', which means today's rain is cancelled – it's their way of saying that the hairless head is like a clear sky.")

d35 = Destination.create(location: "Panorama Route, South Africa", img_url: "https://s27135.pcdn.co/wp-content/uploads/2016/11/Panorama-Route-South-Africa.jpg.optimal.jpg", description: "The Panorama Route is a scenic road in South Africa connecting several cultural and natural points of interest. ... The route is centred around the Blyde River Canyon, the world's third largest canyon, and features numerous waterfalls, one of the largest afforested areas in South Africa, and several natural landmarks. The route starts at the foot of the Long Tom Pass just outside Lydenburg, following the natural descent from the Great Escarpment to the Lowveld, and ending at the border of the Mpumalanga and Limpopo provinces near the Echo Caves. 
This route is deeply entrenched in the history of South Africa. From 1871, parts of the route were used as a transport road between Lydenburg and Delagoa Bay. It is also on this route that General Louis Botha fled from the English during the Anglo Boer War, and houses one of the most famous Victorian age canons in the world, “The Long Tom”.
Many towns on the route, such as Pilgrim’s Rest, were established during the Transvaal gold rush in the late 1800s. Thousands of fortune seekers crossed the treacherous mountains and rugged terrain in the search of gold. One of these was a former storekeeper from Pilgrim’s Rest, Percy Fitzpatrick. He wrote the popular book Jock of the Bushveld, recounting some of the adventures he shared with his faithful bull terrier Jock, whilst traversing this famous route.")
